//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrideFemale
    {
        public int id { get; set; }
        public string FemaleNIK { get; set; }
        public string FemaleName { get; set; }
        public string FemaleBirthPlace { get; set; }
        public Nullable<System.DateTime> FemaleBirthDate { get; set; }
        public string FemaleAddress { get; set; }
        public string FemalePhone { get; set; }
        public string FemaleCivil { get; set; }
        public string FemaleReligion { get; set; }
        public string FemaleWork { get; set; }
        public string FemaleFatherNIK { get; set; }
        public string FemaleMotherNIK { get; set; }
    }
}
