//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrideMale
    {
        public int id { get; set; }
        public string PriaNIK { get; set; }
        public string PriaName { get; set; }
        public string PriaBirthPlace { get; set; }
        public Nullable<System.DateTime> PriaBirthDate { get; set; }
        public string PriaAddress { get; set; }
        public string PriaPhone { get; set; }
        public string PriaCivil { get; set; }
        public string PriaReligion { get; set; }
        public string PriaWork { get; set; }
        public string MaleFatherNIK { get; set; }
        public string MaleMotheNIK { get; set; }
    }
}
