//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class FemaleMother
    {
        public int id { get; set; }
        public string WanitaMotherNIK { get; set; }
        public string WanitaMotherName { get; set; }
        public string WanitaMotherBirthPlace { get; set; }
        public Nullable<System.DateTime> WanitaMotherBirthDate { get; set; }
        public string WanitaMotherCivil { get; set; }
        public string WanitaMotherReligion { get; set; }
    }
}
