//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class FemaleFather
    {
        public int id { get; set; }
        public string WanitaFatherNIK { get; set; }
        public string WanitaFatherName { get; set; }
        public string WanitaFatherBirthPlace { get; set; }
        public Nullable<System.DateTime> WanitaFatherBirthDate { get; set; }
        public string WanitaFatherCivil { get; set; }
        public string WanitaFatherReligion { get; set; }
    }
}
