//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaleFather
    {
        public int id { get; set; }
        public string PriaFatherNIK { get; set; }
        public string PriaFatherName { get; set; }
        public string PriaFatherBirthPlace { get; set; }
        public Nullable<System.DateTime> PriaFatherBirthDate { get; set; }
        public string PriaFatherCivil { get; set; }
        public string PriaFatherReligion { get; set; }
    }
}
