//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaleMother
    {
        public int id { get; set; }
        public string PriaMotherNIK { get; set; }
        public string PriaMotherName { get; set; }
        public string PriaMotherBirthPlace { get; set; }
        public Nullable<System.DateTime> PriaMotherBirthDate { get; set; }
        public string PriaMotherCivil { get; set; }
        public string PriaMotherReligion { get; set; }
    }
}
