//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NikahEntities : DbContext
    {
        public NikahEntities()
            : base("name=NikahEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BrideFemale> BrideFemales { get; set; }
        public virtual DbSet<BrideMale> BrideMales { get; set; }
        public virtual DbSet<FemaleFather> FemaleFathers { get; set; }
        public virtual DbSet<FemaleMother> FemaleMothers { get; set; }
        public virtual DbSet<MaleFather> MaleFathers { get; set; }
        public virtual DbSet<MaleMother> MaleMothers { get; set; }
        public virtual DbSet<Planning> Plannings { get; set; }
        public virtual DbSet<Saksi> Saksis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
