//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planning
    {
        public int id { get; set; }
        public string NikahAddress { get; set; }
        public string NikahPhone { get; set; }
        public Nullable<System.DateTime> NikahDate { get; set; }
        public string NikahDescription { get; set; }
        public string PasanganPria { get; set; }
        public string PasanganWanita { get; set; }
        public string CatatSaksiSatu { get; set; }
        public string CatatSaksiDua { get; set; }
    }
}
