//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saksi
    {
        public int id { get; set; }
        public string SaksiSatuName { get; set; }
        public string SaksiSatuAddress { get; set; }
        public string SaksiDuaName { get; set; }
        public string SaksiDuaAddress { get; set; }
    }
}
